name: DEPTRY

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: ./.github/actions/environment

      - name: Install and run deptry
        run: |
          python -m pip install --no-cache-dir deptry
          deptry finmarketpy
